'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowLeft,ShieldCheck,CheckCircle2,Users,Trash2,Plus} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {profileSchema,type Profile,type rankSchemes} from '@/lib/domain';
import {Choice,PageTitle,SampleNotice,api,track,Empty,Status} from './site';
type Result=ReturnType<typeof rankSchemes>;
const unknown={value:'unknown',label:'अभी नहीं बताना चाहते'};
export function ProfileFields({p,set,step}:{p:Profile;set:(p:Profile)=>void;step?:number}){function update(key:keyof Profile,value:unknown){set({...p,[key]:value==='unknown'?undefined:value});}return <div className="form-grid">{(step===undefined||step===0)&&<><label className="field">आप कहाँ रहते हैं?<Choice label="निवास राज्य" value={p.state??'unknown'} onChange={v=>update('state',v)} options={[unknown,{value:'madhya-pradesh',label:'मध्य प्रदेश'},{value:'other',label:'अन्य राज्य'}]}/></label><label className="field">आपका क्षेत्र<Choice label="ग्रामीण या शहरी" value={p.rural===undefined?'unknown':String(p.rural)} onChange={v=>update('rural',v==='unknown'?undefined:v==='true')} options={[unknown,{value:'true',label:'ग्रामीण'},{value:'false',label:'शहरी'}]}/></label></>}{(step===undefined||step===1)&&<><label className="field">उम्र (वर्ष)<input type="number" min="0" max="120" placeholder="जैसे: 35" value={p.age??''} onChange={e=>update('age',e.target.value===''?undefined:Number(e.target.value))}/><small>जन्म तारीख या पहचान पत्र की ज़रूरत नहीं।</small></label><label className="field">लिंग<Choice label="लिंग" value={p.gender??'unknown'} onChange={v=>update('gender',v)} options={[unknown,{value:'female',label:'महिला'},{value:'male',label:'पुरुष'},{value:'other',label:'अन्य'}]}/></label></>}{(step===undefined||step===2)&&<><label className="field">आप क्या करते हैं?<Choice label="काम या व्यवसाय" value={p.occupation??'unknown'} onChange={v=>update('occupation',v)} options={[unknown,{value:'farmer',label:'किसान'},{value:'student',label:'विद्यार्थी'},{value:'worker',label:'नौकरी / श्रमिक'},{value:'self-employed',label:'स्वरोज़गार'},{value:'other',label:'अन्य'}]}/></label><label className="field">परिवार की सालाना आय (₹)<input type="number" min="0" max="100000000" placeholder="वैकल्पिक" value={p.income??''} onChange={e=>update('income',e.target.value===''?undefined:Number(e.target.value))}/><small>लगभग राशि बताएँ। बैंक की जानकारी न दें।</small></label></>}</div>;}
export function Results({results}:{results:Result}){return <><SampleNotice/><p className="small" style={{marginBottom:20}}>नतीजे सिर्फ दर्ज नियमों पर आधारित हैं। अधूरी शर्तें और अपवाद सरकारी स्रोत पर जाँचें। “मिलान” सरकारी पात्रता का निर्णय नहीं है।</p>{!results.length?<Empty title="इन जवाबों से कोई योजना नहीं मिली" description="आपके जवाब से मेल खाती योजना अभी हमारे संग्रह में नहीं है। बाद में फिर देखें।"/>:results.map(r=><article className="result-row" key={r.scheme.slug}><div className="row-between"><Status s={r.scheme}/><span className="badge">{r.reasons.length===0?'नियम उपलब्ध नहीं':`${r.score}% दर्ज नियमों से मिलान`}</span></div><h3><Link href={'/yojna/'+r.scheme.slug}>{r.scheme.title}</Link></h3><p>{r.scheme.benefit}</p><ul className="reason-list">{r.reasons.map((v,i)=><li key={i}>{v.result==='match'?'✓':'?'} {v.label} — {v.result==='match'?'आपके जवाब से मेल':'जानकारी बाकी'}</li>)}</ul>{r.missing>0&&<p>{r.missing} शर्तों की जानकारी बाकी है। पूरा मिलान जाँचने के लिए जवाब जोड़ें।</p>}<Link href={'/yojna/'+r.scheme.slug}>पूरी जानकारी देखें →</Link></article>)}</>;}
export function Eligibility(){const [step,setStep]=useState(0),[p,setP]=useState<Profile>({}),[results,setResults]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
async function next(){setError('');if(!profileSchema.safeParse(p).success){setError('उम्र 0–120 वर्ष और आय शून्य या उससे अधिक रखें।');return;}if(step<2){setStep(step+1);if(step===0)track('wizard_started');return;}setBusy(true);try{setResults(await api<Result>('/api/eligibility',p));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <main id="main" className="page-wrap"><div className="wizard"><PageTitle eyebrow="मेरे लिए योजनाएं" title={results?'आपके लिए संभावित योजनाएं':'थोड़ा आपके बारे में, ताकि मदद सही मिले।'} description="तीन छोटे कदम। कोई अकाउंट, आधार नंबर या फोन नंबर नहीं। आप कोई भी जवाब छोड़ सकते हैं।"/>{results?<><button className="btn secondary" onClick={()=>setResults(null)} style={{marginBottom:25}}><ArrowLeft size={16}/>जवाब बदलें</button><Results results={results}/><Link className="btn" href="/family"><Users size={18}/>परिवार के लिए भी खोजें</Link></>:<><div className="wizard-steps">{['01 · निवास','02 · आपके बारे में','03 · काम और आय'].map((s,i)=><span className={step===i?'current':''} key={s}>{s}</span>)}</div><Progress value={(step+1)*100/3} aria-label="प्रगति"/><section className="panel"><h2>{['आप कहाँ रहते हैं?','आपके बारे में थोड़ी जानकारी','आपकी रोज़मर्रा की स्थिति'][step]}</h2><p>इन जवाबों से योजनाओं के दर्ज नियमों का मिलान होगा।</p><ProfileFields p={p} set={setP} step={step}/>{error&&<p role="alert" className="error-message">{error}</p>}<div className="form-actions">{step>0&&<button className="btn secondary" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/>पीछे</button>}<button className="btn" disabled={busy} onClick={next}>{busy?'योजनाएं खोज रहे हैं…':step===2?'मेरी योजनाएं देखें':'आगे बढ़ें'}<ArrowRight size={16}/></button></div></section><p className="check-label"><ShieldCheck size={19}/>आपके जवाब डेटाबेस में सहेजे नहीं जाते। पात्रता जाँच पूरी सरकारी प्रक्रिया का विकल्प नहीं है।</p></>}</div></main>;}
type Member={id:string;label:string;profile:Profile};
export function Family(){const [members,setMembers]=useState<Member[]>([]),[p,setP]=useState<Profile>({}),[label,setLabel]=useState('स्वयं'),[open,setOpen]=useState(false),[save,setSave]=useState(false),[results,setResults]=useState<{label:string;results:Result}[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem('sy_family')??'null');if(stored&&stored.expires>Date.now()){const valid=stored.members.filter((m:Member)=>profileSchema.safeParse(m.profile).success);setMembers(valid);setSave(true);}else localStorage.removeItem('sy_family');}catch{localStorage.removeItem('sy_family');}},[]);
function persist(next:Member[],opt=save){setMembers(next);setResults([]);try{if(opt)localStorage.setItem('sy_family',JSON.stringify({members:next,expires:Date.now()+30*86400000}));else localStorage.removeItem('sy_family');}catch{setError('इस डिवाइस पर सहेजना उपलब्ध नहीं है। जानकारी इस पेज पर ही रहेगी।');}}
function add(){if(!profileSchema.safeParse(p).success){setError('उम्र और आय सही भरें।');return;}persist([...members,{id:crypto.randomUUID(),label,profile:p}]);setOpen(false);setP({});setError('');}
async function find(){setBusy(true);setError('');try{const r=[];for(const m of members)r.push({label:m.label,results:await api<Result>('/api/eligibility',m.profile)});setResults(r);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <main id="main" className="page-wrap"><PageTitle eyebrow="मेरा परिवार" title="एक परिवार। हर सदस्य के लिए अवसर।" description="नाम या पहचान पत्र की ज़रूरत नहीं। हर सदस्य की स्थिति जोड़ें और उनके लिए अलग सुझाव देखें।"/><div className="panel"><div className="row-between"><h2>परिवार के सदस्य <span className="badge">{members.length} / 8</span></h2><button className="btn secondary" disabled={members.length>=8} onClick={()=>setOpen(true)}><Plus size={17}/>सदस्य जोड़ें</button></div>{!members.length?<p className="small">पहला सदस्य जोड़कर शुरू करें। बिना सहेजे भी सुझाव मिलेंगे।</p>:members.map(m=><div className="result-row row-between" key={m.id}><div><b>{m.label}</b><p>{m.profile.age===undefined?'उम्र नहीं बताई':m.profile.age+' वर्ष'} · {m.profile.state==='madhya-pradesh'?'मध्य प्रदेश':m.profile.state==='other'?'अन्य राज्य':'निवास नहीं बताया'}</p></div><button className="icon-link" aria-label={m.label+' हटाएं'} onClick={()=>persist(members.filter(x=>x.id!==m.id))}><Trash2 size={18}/></button></div>)}<label className="check-label"><Checkbox checked={save} onCheckedChange={v=>{setSave(v===true);persist(members,v===true);}}/>मैं अपनी और वयस्क सदस्यों की अनुमति से यह जानकारी इस डिवाइस पर 30 दिन सहेजना चाहता/चाहती हूँ। साझा डिवाइस पर यह विकल्प न चुनें।</label><p className="small">बच्चों के लिए केवल उनके माता-पिता या अभिभावक जानकारी जोड़ें।</p><div className="form-actions"><button className="btn" disabled={!members.length||busy} onClick={find}>{busy?'सुझाव खोज रहे हैं…':'परिवार की योजनाएं देखें'}<ArrowRight size={17}/></button></div></div>{error&&<p role="alert" className="error-message">{error}</p>}{results.map((r,i)=><section key={i}><h2 style={{margin:'25px 0 15px'}}>{r.label} के लिए</h2><Results results={r.results}/></section>)}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogTitle>परिवार का सदस्य जोड़ें</DialogTitle><DialogDescription>पहचान की जानकारी साझा न करें। सभी जवाब वैकल्पिक हैं।</DialogDescription><label className="field">सदस्य<Choice label="संबंध" value={label} onChange={setLabel} options={['स्वयं','जीवनसाथी','माता','पिता','बच्चा','अन्य सदस्य'].map(x=>({value:x,label:x}))}/></label><ProfileFields p={p} set={setP}/>{error&&<p role="alert" className="error-message">{error}</p>}<button className="btn" onClick={add}><CheckCircle2 size={17}/>जोड़ें</button></DialogContent></Dialog></main>;}
