'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Bell,Download,Trash2,Bookmark} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {PageTitle,api,Card,Empty} from './site';
import type {Scheme} from '@/lib/domain';
type Reminder={id:string;slug:string;title:string;date:string};
export function Reminders(){const [items,setItems]=useState<Reminder[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
useEffect(()=>{api<Reminder[]>('/api/reminders',undefined,'GET').then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
async function remove(id:string){try{await api('/api/reminders',{id},'DELETE');setItems(items.filter(x=>x.id!==id));toast.success('रिमाइंडर हटा दिया गया।');}catch(e){toast.error((e as Error).message);}}
function calendar(r:Reminder){const escaped=r.title.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Sarkari Yojna//Reminder//HI','BEGIN:VEVENT',`UID:${r.id}@sarkari-yojna`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${r.date.replaceAll('-','')}`,`SUMMARY:${escaped} - जानकारी जाँचें`,`DESCRIPTION:यह व्यक्तिगत रिमाइंडर है। आवेदन की अंतिम तारीख नहीं।`,`URL:${location.origin}/yojna/${r.slug}`,'BEGIN:VALARM','TRIGGER:-PT9H','ACTION:DISPLAY','DESCRIPTION:योजना की जानकारी जाँचें','END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='yojna-reminder.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
return <main id="main" className="page-wrap"><PageTitle eyebrow="मेरे रिमाइंडर" title="ज़रूरी बातें, सही समय पर।" description="अपने चुने हुए दिन योजना की जानकारी फिर जाँचें। फोन संदेश नहीं भेजे जाते; कैलेंडर में जोड़कर अपने डिवाइस की सूचना इस्तेमाल करें।"/>{error?<p role="alert" className="error-message">{error}</p>:loading?<p role="status">रिमाइंडर लोड हो रहे हैं…</p>:!items.length?<Empty title="अभी कोई रिमाइंडर नहीं है" description="किसी योजना को खोलें और ‘मुझे याद दिलाएं’ चुनें।"/>:items.map(r=><article className="result-row row-between" key={r.id}><div><span className="badge"><Bell size={14}/>&nbsp;{new Date(r.date+'T12:00:00').toLocaleDateString('hi-IN')}{r.date<=new Date().toISOString().slice(0,10)?' · अब जाँचें':''}</span><h3><Link href={'/yojna/'+r.slug}>{r.title}</Link></h3></div><div className="form-actions" style={{margin:0}}><button className="btn secondary" onClick={()=>calendar(r)}><Download size={16}/>कैलेंडर</button><button className="icon-link" aria-label="रिमाइंडर हटाएं" onClick={()=>remove(r.id)}><Trash2 size={18}/></button></div></article>)}</main>;}
export function Saved({schemes}:{schemes:Scheme[]}){const [ids,setIds]=useState<string[]>([]),[ready,setReady]=useState(false);useEffect(()=>{try{setIds(JSON.parse(localStorage.getItem('sy_saved')??'[]'));}catch{}setReady(true);},[]);return <main id="main" className="page-wrap"><PageTitle eyebrow="सहेजी योजनाएं" title="जो आपके काम आए, उसे पास रखें।" description="यह सूची केवल इस ब्राउज़र में रहती है। किसी योजना के पेज पर जाकर उसे सहेज या हटा सकते हैं।"/>{!ready?<p>लोड हो रहा है…</p>:ids.length?<div className="scheme-grid">{schemes.filter(s=>ids.includes(s.slug)).map(s=><Card key={s.slug} s={s}/>)}</div>:<Empty title="आपकी सूची अभी खाली है" description="योजना के पेज पर ‘बाद के लिए सहेजें’ चुनें।"/>}</main>;}
export function DeleteData(){const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');async function remove(){setBusy(true);try{await api('/api/privacy',{},'DELETE');['sy_saved','sy_family'].forEach(k=>localStorage.removeItem(k));setOpen(false);toast.success('इस ब्राउज़र से जुड़ी निजी जानकारी हटा दी गई।');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <><button className="btn secondary" onClick={()=>setOpen(true)}><Trash2 size={16}/>मेरी सहेजी जानकारी हटाएं</button><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogTitle>सहेजी जानकारी हटाएं?</DialogTitle><DialogDescription>इस ब्राउज़र का परिवार, सहेजी योजनाएं, रिमाइंडर और प्रतिक्रिया हटा दिए जाएंगे। इन्हें वापस नहीं लाया जा सकेगा।</DialogDescription>{error&&<p role="alert">{error}</p>}<button className="btn" disabled={busy} onClick={remove}>{busy?'हटा रहे हैं…':'हाँ, मेरी जानकारी हटाएं'}</button></DialogContent></Dialog></>;}
