'use client';
import {useEffect,useState} from 'react';
import {Bookmark,Bell,ThumbsUp,Flag,ExternalLink} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Choice,api,track} from './site';
import type {Scheme} from '@/lib/domain';
export function SchemeActions({s,initialCount}:{s:Scheme;initialCount:number}){const [saved,setSaved]=useState(false),[modal,setModal]=useState(''),[date,setDate]=useState(''),[reason,setReason]=useState('outdated'),[detail,setDetail]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[count,setCount]=useState(initialCount);
useEffect(()=>{track('scheme_opened');try{setSaved(JSON.parse(localStorage.getItem('sy_saved')??'[]').includes(s.slug));}catch{}},[s.slug]);
function bookmark(){try{const current:string[]=JSON.parse(localStorage.getItem('sy_saved')??'[]');localStorage.setItem('sy_saved',JSON.stringify(saved?current.filter(x=>x!==s.slug):[...new Set([...current,s.slug])]));setSaved(!saved);toast.success(saved?'योजना हटा दी गई।':'योजना इस डिवाइस पर सहेज ली गई।');}catch{toast.error('इस डिवाइस पर सहेजना उपलब्ध नहीं है।');}}
async function submit(){setBusy(true);setError('');try{await api(modal==='report'?'/api/reports':'/api/reminders',modal==='report'?{slug:s.slug,reason,detail}:{slug:s.slug,date});setModal('');toast.success(modal==='report'?'आपकी रिपोर्ट मिल गई। धन्यवाद।':'रिमाइंडर सहेजा गया। मेरे रिमाइंडर में देखें।');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function vote(){setBusy(true);try{const r=await api<{count:number}>('/api/signals',{slug:s.slug});setCount(r.count);toast.success('आपकी प्रतिक्रिया दर्ज है।');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
return <><div className="panel"><h2>अगला कदम</h2>{s.applicationUrl&&!['CLOSED','ARCHIVED'].includes(s.status)?<a className="btn" href={'/out/'+s.slug+'?kind=application'} target="_blank" rel="noopener noreferrer">official आवेदन खोलें<ExternalLink size={16}/></a>:<div className="sample-note">सत्यापित आवेदन लिंक अभी उपलब्ध नहीं है।</div>}{s.sourceUrl&&<a className="btn secondary" href={'/out/'+s.slug+'?kind=source'} target="_blank" rel="noopener noreferrer">सरकारी स्रोत देखें<ExternalLink size={16}/></a>}<button className="btn secondary" onClick={bookmark}><Bookmark size={17} fill={saved?'currentColor':'none'}/>{saved?'सहेजी गई · हटाएं':'बाद के लिए सहेजें'}</button><button className="btn secondary" disabled={['CLOSED','ARCHIVED'].includes(s.status)} onClick={()=>{setModal('reminder');setError('');}}><Bell size={17}/>मुझे याद दिलाएं</button><p>यहाँ कोई आवेदन या भुगतान नहीं लिया जाता।</p></div><div className="panel"><h3>क्या जानकारी मददगार लगी?</h3><p>{count} लोगों ने जानकारी सही लगने की प्रतिक्रिया दी। यह सरकारी सत्यापन नहीं है।</p><button className="btn secondary" disabled={busy} onClick={vote}><ThumbsUp size={16}/>यह जानकारी सही लगी</button><button className="text-button" onClick={()=>{setModal('report');setError('');}}><Flag size={15}/>क्या इस जानकारी में गलती है?</button></div><Dialog open={!!modal} onOpenChange={v=>{if(!v)setModal('');}}><DialogContent><DialogTitle>{modal==='report'?'जानकारी में गलती बताएं':'एक छोटा-सा रिमाइंडर'}</DialogTitle><DialogDescription>{modal==='report'?'हमारी समीक्षा टीम इसे जाँचेगी। व्यक्तिगत जानकारी न भेजें।':'रिमाइंडर इसी ब्राउज़र में 90 दिन तक रहेगा। SMS या WhatsApp नहीं भेजे जाते। कैलेंडर डाउनलोड भी उपलब्ध है।'}</DialogDescription>{modal==='report'?<><label className="field">क्या गलत है?<Choice label="रिपोर्ट का कारण" value={reason} onChange={setReason} options={[{value:'wrong-benefit',label:'लाभ की जानकारी'},{value:'wrong-eligibility',label:'पात्रता की जानकारी'},{value:'broken-link',label:'लिंक नहीं खुलता'},{value:'closed',label:'योजना बंद है'},{value:'outdated',label:'पुरानी जानकारी'},{value:'contact',label:'गलत संपर्क'},{value:'other',label:'अन्य'}]}/></label><label className="field">थोड़ा और बताएं (वैकल्पिक)<textarea maxLength={1000} value={detail} onChange={e=>setDetail(e.target.value)}/></label></>:<label className="field">किस दिन याद करना है?<input type="date" value={date} min={new Date().toISOString().slice(0,10)} max={new Date(Date.now()+89*86400000).toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/><small>रिमाइंडर सहेजने से एक आवश्यक session cookie बनेगी। यह आवेदन की अंतिम तारीख नहीं है।</small></label>}{error&&<p role="alert" className="error-message">{error}</p>}<button className="btn" disabled={busy||(modal==='reminder'&&!date)} onClick={submit}>{busy?'सहेज रहे हैं…':modal==='report'?'रिपोर्ट भेजें':'रिमाइंडर सहेजें'}</button></DialogContent></Dialog></>;}
