'use client';
import Link from 'next/link';
import {OfficialImage} from './official-image';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {Sprout,HeartHandshake,GraduationCap,HeartPulse,House,BriefcaseBusiness,Accessibility,Wheat,ArrowUpRight,ArrowRight,ShieldCheck,MapPin,Menu,Search,Users,Bookmark,Bell,Compass,Info,Check,ChevronRight} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {categories,statusLabels,type Scheme} from '@/lib/domain';
export const icons={Sprout,HeartHandshake,GraduationCap,HeartPulse,House,BriefcaseBusiness,Accessibility,Wheat};
export async function api<T>(path:string,data?:unknown,method='POST'):Promise<T>{const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});const b=await r.json() as T & {error?:string};if(!r.ok)throw Error(b.error??'कुछ गलत हुआ। फिर कोशिश करें।');return b;}
export function track(name:string){void api('/api/events',{name}).catch(()=>{});}
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
export function Header(){const path=usePathname();const [open,setOpen]=useState(false);return <><a className="skip" href="#main">मुख्य सामग्री पर जाएं</a><div className="independent"><div><ShieldCheck size={14}/>एक स्वतंत्र पहल। सरकारी वेबसाइट नहीं है।</div><span>आपकी जानकारी, आपकी भाषा में</span></div><header className="site-header"><Link href="/" className="brand"><span className="brand-mark"><Sprout size={27}/></span><span>सरकारी योजना<small>SARKARI YOJNA</small></span></Link><nav aria-label="मुख्य नेविगेशन" className={open?'nav open':'nav'}>{[{href:'/',label:'योजनाएं खोजें'},{href:'/mere-liye',label:'मेरे लिए योजनाएं'},{href:'/family',label:'मेरा परिवार'},{href:'/guide',label:'आसान गाइड'}].map(n=><Link onClick={()=>setOpen(false)} className={path===n.href?'active':''} key={n.href} href={n.href}>{n.label}</Link>)}</nav><div className="header-end"><span className="language">अ <span>हिन्दी</span></span><Link href="/saved" className="icon-link" aria-label="सहेजी योजनाएं"><Bookmark size={20}/></Link><Link href="/reminders" className="icon-link" aria-label="मेरे रिमाइंडर"><Bell size={20}/></Link><button className="mobile-menu icon-link" aria-label="मेन्यू" aria-expanded={open} onClick={()=>setOpen(!open)}><Menu/></button></div></header></>;}
export function Footer(){return <footer className="footer"><div className="footer-brand"><Sprout size={22}/><b>सही जानकारी। बेहतर अवसर।</b></div><p>Sarkari Yojna सरकारी वेबसाइट नहीं है। आवेदन केवल संबंधित official government portal पर करें।</p><div className="footer-bottom"><span>बुनियादी योजना खोज हमेशा निःशुल्क।</span><nav><Link href="/privacy">गोपनीयता</Link><Link href="/terms">शर्तें</Link><Link href="/disclaimer">अस्वीकरण</Link><Link href="/admin">व्यवस्थापक</Link></nav></div></footer>;}
export function Sidebar({category='all'}:{category?:string}){return <aside className="sidebar"><p className="eyebrow">आपके लिए</p><Link className={category==='all'?'side-item selected':'side-item'} href="/"><Compass size={19}/>योजनाएं खोजें<ChevronRight size={15}/></Link><Link className="side-item" href="/mere-liye"><Users size={19}/>मेरे लिए योजनाएं</Link><Link className="side-item" href="/saved"><Bookmark size={19}/>सहेजी योजनाएं</Link><Link className="side-item" href="/reminders"><Bell size={19}/>मेरे रिमाइंडर</Link><div className="side-rule"/><p className="eyebrow">श्रेणी के अनुसार</p>{categories.map(c=>{const Icon=icons[c.icon];return <Link onClick={()=>track('category_opened')} href={'/category/'+c.id} key={c.id} className={'side-item '+(category===c.id?'selected':'')}><Icon size={18}/>{c.short}</Link>})}<div className="sidebar-help"><ShieldCheck size={24}/><h3>आपकी सुरक्षा पहले</h3><p>OTP, UPI PIN या bank password किसी के साथ साझा न करें।</p><Link href="/disclaimer">सुरक्षित रहें <ArrowUpRight size={14}/></Link></div></aside>;}
export function Status({s}:{s:Scheme}){return <span className={'status '+(s.status==='ACTIVE'?'verified':'')}><span/>{statusLabels[s.status]}</span>;}
export function Card({s}:{s:Scheme}){const cat=categories.find(c=>c.id===s.category)!;const Icon=icons[cat.icon];return <article className="scheme-card"><OfficialImage slug={s.slug}/><div className="card-top"><span className={'category-icon '+cat.color}><Icon size={23}/></span><span className="scope"><MapPin size={13}/>{s.state==='central'?'केंद्र सरकार':'मध्य प्रदेश'}</span></div><Link href={'/yojna/'+s.slug} className="card-title"><h3>{s.title}</h3></Link><p className="english">{s.english}</p><p className="card-summary">{s.summary}</p><div className="benefit"><Check size={16}/><span>{s.benefit}</span></div><div className="card-bottom"><Status s={s}/><Link href={'/yojna/'+s.slug} aria-label={s.title+' देखें'}><ArrowRight size={20}/></Link></div></article>;}
export function Empty({title='अभी कोई योजना नहीं मिली',description='दूसरी श्रेणी चुनें या खोज के शब्द बदलकर देखें।'}:{title?:string;description?:string}){return <div className="empty"><Search size={32}/><h2>{title}</h2><p>{description}</p><Link className="btn secondary" href="/">सभी योजनाएं देखें <ArrowRight size={17}/></Link></div>;}
export function PageTitle({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="page-heading"><p className="eyebrow green-text">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>;}
export function SampleNotice(){return <div className="sample-note"><Info size={17}/><span><b>डेमो जानकारी:</b> इन रिकॉर्ड की पूरी सरकारी पुष्टि बाकी है। पात्रता के नतीजे संकेत हैं, लाभ की गारंटी नहीं।</span></div>;}
