export const officialImages: Record<string, {
  src: string; alt: string; source: string; credit: string; width: number; height: number }> = {
  'mukhyamantri-arthik-kalyan-tribal-yojana': { src: '/mukhyamantri-arthik-kalyan-tribal-yojana.jpg', alt: 'मध्य प्रदेश मुख्यमंत्री आर्थिक कल्याण योजना (जनजातीय) बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mukhyamantri-swarojgar-yojana-general': { src: '/mukhyamantri-swarojgar-yojana-general.jpg', alt: 'मध्य प्रदेश मुख्यमंत्री स्वरोजगार योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mukhyamantri-krishak-udyami-yojana': { src: '/mukhyamantri-krishak-udyami-yojana.png', alt: 'मध्य प्रदेश मुख्यमंत्री कृषक उद्यमी योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mp-mukhyamantri-udyam-kranti-yojana': { src: '/mp-mukhyamantri-udyam-kranti-yojana.png', alt: 'मध्य प्रदेश मुख्यमंत्री उद्यम क्रांति योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'yuva-annadoot-yojana': { src: '/yuva-annadoot-yojana.png', alt: 'मध्य प्रदेश मुख्यमंत्री युवा अन्नदूत योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'ration-aapke-dwar-yojana': { src: '/ration-aapke-dwar-yojana.png', alt: 'मध्य प्रदेश मुख्यमंत्री राशन आपके द्वार योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'padho-aur-padhao-yojana': { src: '/padho-aur-padhao-yojana.jpg', alt: 'मध्य प्रदेश पढ़ो और पढ़ाओ योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'covid-19-bal-kalyan-yojana': { src: '/covid-19-bal-kalyan-yojana.jpg', alt: 'मध्य प्रदेश मुख्यमंत्री कोविड-19 बाल कल्याण योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'bal-aashirwad-yojana': { src: '/bal-aashirwad-yojana.jpg', alt: 'मध्य प्रदेश मुख्यमंत्री बाल आशीर्वाद योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mukhyamantri-gas-cylinder-subsidy-yojana': { src: '/mukhyamantri-gas-cylinder-subsidy-yojana.jpg', alt: 'मध्य प्रदेश मुख्यमंत्री गैस सिलिंडर सब्सिडी योजना बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'pm-kisan': { src: '/08_pm_kisan_samman_nidhi.webp', alt: 'pm-kisan का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'ladli-behna': { src: '/ladli-behna-official.webp', alt: 'ladli-behna का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'seekho-kamao': { src: '/04_mukhyamantri_seekho_kamao_yojana.webp', alt: 'seekho-kamao का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'kisan-kalyan': { src: '/07_mukhyamantri_kisan_kalyan_yojana.webp', alt: 'kisan-kalyan का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'gaon-ki-beti': { src: '/gaon-ki-beti-banner.webp', alt: 'गांव की बेटी योजना — ग्रामीण छात्राओं के लिए छात्रवृत्ति बैनर', source: 'https://scholarshipportal.mp.nic.in/', credit: 'उच्च शिक्षा विभाग, मध्य प्रदेश', width: 1200, height: 400 },
  'sambal-yojana': { src: '/sambal-yojna-banner.webp', alt: 'मुख्यमंत्री जन कल्याण संबल योजना — असंगठित श्रमिकों के लिए बैनर', source: 'https://sambal.mp.gov.in/', credit: 'श श्रम विभाग, मध्य प्रदेश', width: 1200, height: 400 },
  'ayushman-bharat': { src: '/03_ayushman_bharat_pm_jay.webp', alt: 'ayushman-bharat का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'pm-awas-gramin': { src: '/06_pm_awas_yojana_gramin.webp', alt: 'pm-awas-gramin का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'ration-support': { src: '/ration-support-banner.webp', alt: 'राष्ट्रीय खाद्य सुरक्षा अधिनियम राशन योजना बैनर', source: 'https://nfsa.gov.in/', credit: 'खाद्य एवं सार्वजनिक वितरण विभाग', width: 1200, height: 675 },
  'pm-vishwakarma': { src: '/pm-vishwakarma-banner.webp', alt: 'प्रधानमंत्री विश्वकर्मा योजना आधिकारिक बैनर', source: 'https://pmvishwakarma.gov.in/', credit: 'सूक्ष्म, लघु एवं मध्यम उद्यम मंत्रालय', width: 1200, height: 675 },
  'pm-surya-ghar': { src: '/09_pm_surya_ghar_muft_bijli_yojana.webp', alt: 'pm-surya-ghar का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'pm-mudra': { src: '/pm-mudra-banner.webp', alt: 'प्रधानमंत्री मुद्रा योजना आधिकारिक ऋण बैनर', source: 'https://financialservices.gov.in/', credit: 'वित्तीय सेवाएं विभाग, वित्त मंत्रालय', width: 1200, height: 675 },
  'atal-pension': { src: '/atal-pension-banner.webp', alt: 'अटल पेंशन योजना आधिकारिक पेंशन बैनर', source: 'https://financialservices.gov.in/', credit: 'पेंशन निधि विनियामक और विकास प्राधिकरण', width: 1200, height: 675 },
  'pm-ujjwala': { src: '/pm-ujjwala-banner.webp', alt: 'प्रधानमंत्री उज्ज्वला योजना 2.0 आधिकारिक गैस सब्सिडी बैनर', source: 'https://pmuy.gov.in/', credit: 'पेट्रोलियम एवं प्राकृतिक गैस मंत्रालय', width: 1200, height: 675 },
  'ladli-laxmi': { src: '/ladli-laxmi-banner.webp', alt: 'मुख्यमंत्री लाड़ली लक्ष्मी योजना आधिकारिक बैनर', source: 'https://ladlilaxmi.mp.gov.in/', credit: 'महिला एवं बाल विकास विभाग, मध्य प्रदेश', width: 1200, height: 675 },
  'madhya-pradesh-ladli-laxmi-yojana': { src: '/02_madhya_pradesh_mukhyamantri_ladli_lakshmi_yojana.webp', alt: 'मध्य प्रदेश मुख्यमंत्री लाड़ली लक्ष्मी योजना का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mukhyamantri-seekho-kamao': { src: '/04_mukhyamantri_seekho_kamao_yojana.webp', alt: 'मुख्यमंत्री सीखो कमाओ योजना — युवाओं के लिए कौशल प्रशिक्षण बैनर', source: 'https://mmsky.mp.gov.in/', credit: 'कौशल विकास एवं रोज़गार विभाग, मध्य प्रदेश', width: 1200, height: 675 },
  'mp-gaon-ki-beti': { src: '/gaon-ki-beti-banner.webp', alt: 'गांव की बेटी योजना — ग्रामीण छात्राओं के लिए छात्रवृत्ति बैनर', source: 'https://scholarshipportal.mp.nic.in/', credit: 'उच्च शिक्षा विभाग, मध्य प्रदेश', width: 1200, height: 400 },
  'social-pension': { src: '/social-pension-official.webp', alt: 'समग्र सामाजिक सुरक्षा पेंशन योजना बैनर', source: 'https://socialjustice.mp.gov.in/', credit: 'सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण', width: 1024, height: 1024 },
  'employment-support': { src: '/employment-support-official.webp', alt: 'मुख्यमंत्री उद्यम क्रांति योजना बैनर', source: 'https://msme.mp.gov.in/', credit: 'सूक्ष्म, लघु एवं मध्यम उद्यम विभाग', width: 1024, height: 1024 },
  'mp-board-laptop': { src: '/02_mp_board_laptop_yojana.webp', alt: 'mp-board-laptop का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mp-scholarship': { src: '/05_mp_scholarship_yojana.webp', alt: 'mp-scholarship का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'sukanya-samriddhi': { src: '/sukanya-samriddhi-banner.webp', alt: 'सुकन्या समृद्धि योजना (SSY) आधिकारिक बैनर', source: 'https://nsiindia.gov.in/', credit: 'वित्त मंत्रालय, भारत सरकार', width: 1920, height: 1080 },
  'pm-jeevan-jyoti-bima': { src: '/pmjjby-banner.webp', alt: 'प्रधानमंत्री जीवन ज्योति बीमा योजना (PMJJBY) आधिकारिक बैनर', source: 'https://jansuraksha.gov.in/', credit: 'वित्तीय सेवाएं विभाग, वित्त मंत्रालय', width: 1920, height: 1080 },
  'pm-suraksha-bima': { src: '/pmsby-banner.webp', alt: 'प्रधानमंत्री सुरक्षा बीमा योजना (PMSBY) आधिकारिक बैनर', source: 'https://jansuraksha.gov.in/', credit: 'वित्तीय सेवाएं विभाग, वित्त मंत्रालय', width: 1920, height: 1080 },
  'pm-awas-shahri': { src: '/pm-awas-shahri-banner.webp', alt: 'प्रधानमंत्री आवास योजना – शहरी (PMAY-U) आधिकारिक बैनर', source: 'https://pmaymis.gov.in/', credit: 'आवास और शहरी कार्य मंत्रालय, भारत सरकार', width: 1920, height: 1080 },
  'pm-fasal-bima': { src: '/pm-fasal-bima-banner.webp', alt: 'प्रधानमंत्री फसल बीमा योजना (PMFBY) आधिकारिक बैनर', source: 'https://pmfby.gov.in/', credit: 'कृषि एवं किसान कल्याण विभाग, भारत सरकार', width: 1920, height: 1080 },
  'surajdhara-yojana': { src: '/01_suurjdhara_yojana.webp', alt: 'सूरजधारा योजना का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mukhyamantri-arthik-kalyan-yojana': { src: '/03_mukhyamantri_arthik_kalyan_yojana.webp', alt: 'मुख्यमंत्री आर्थिक कल्याण योजना का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mukhyamantri-kanya-vivah-yojana': { src: '/04_madhya_pradesh_mukhyamantri_kanya_vivah_yojana.webp', alt: 'मध्य प्रदेश मुख्यमंत्री कन्या विवाह योजना का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mukhyamantri-teerth-darshan-yojana': { src: '/05_madhya_pradesh_mukhyamantri_tirth_darshan_yojana.webp', alt: 'मध्यप्रदेश मुख्यमंत्री तीर्थ दर्शन योजना का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'mausam-aadharit-fasal-bima-yojana': { src: '/06_mausam_aadharit_fasal_bima_yojana.webp', alt: 'मौसम आधारित फसल बीमा योजना का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'phal-paudh-ropan-yojana': { src: '/07_phal_paudh_ropan_yojana.webp', alt: 'फल पौध रोपण योजना का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'masala-kshetra-vistar-yojana': { src: '/08_masala_kshetra_vistar_yojana.webp', alt: 'मसाला क्षेत्र विस्तार योजना का आधिकारिक बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 },
  'sabzi-kshetra-vistar-yojana': { src: '/09_sabzi_kshetra_vistar_yojana.png', alt: 'सब्ज़ी क्षेत्र विस्तार योजना का बैनर', source: '#', credit: 'मध्य प्रदेश शासन', width: 1200, height: 675 }
};
