import type { Scheme } from './domain';
import {officialContent} from './official-content.ts';
import {mpSchemes} from './mp-schemes-data.ts';
const base={department:'संबंधित सरकारी विभाग',documents:['दस्तावेजों की सूची official portal पर जाँचें।'],steps:['पहले official source पर वर्तमान शर्तें पढ़ें।','दस्तावेजों और आवेदन के तरीके की पुष्टि करें।','आवेदन केवल संबंधित सरकारी पोर्टल या अधिकृत केंद्र पर करें।'],sourceNotes:'डेमो रिकॉर्ड। संक्षिप्त विवरण और पात्रता नियम केवल उत्पाद का अनुभव दिखाने के लिए हैं। पूरी सरकारी शर्तों का सत्यापन बाकी है।',applicationUrl:'',status:'REQUIRES_OFFICIAL_VERIFICATION' as const,isSample:true,verifiedAt:null,nextReviewAt:null};
const originalSeeds:Scheme[]=[
 {...base,slug:'pm-kisan',title:'प्रधानमंत्री किसान सम्मान निधि',english:'PM Kisan Samman Nidhi',category:'kisan',state:'central',summary:'किसान परिवारों के लिए आय सहायता की योजना। लाभ और पूरी पात्रता की पुष्टि सरकारी पोर्टल पर करें।',benefit:'किसान परिवारों के लिए आर्थिक सहायता',department:'कृषि एवं किसान कल्याण विभाग',sourceUrl:'https://pmkisan.gov.in/',priority:true,rules:[{field:'occupation',op:'eq',value:'farmer',label:'कृषि से जुड़े नागरिक (उदाहरण नियम)'}]},
 {...base,slug:'ladli-behna',title:'मुख्यमंत्री लाड़ली बहना योजना',english:'Mukhyamantri Ladli Behna Yojana',category:'mahila',state:'madhya-pradesh',summary:'मध्य प्रदेश की महिलाओं के लिए सहायता। वर्तमान लाभ, आयु सीमा और आवेदन की उपलब्धता की पुष्टि आवश्यक है।',benefit:'महिलाओं की आर्थिक भागीदारी के लिए सहायता',sourceUrl:'',priority:true,rules:[{field:'gender',op:'eq',value:'female',label:'महिलाओं के लिए (उदाहरण नियम)'}]},
 {...base,slug:'ayushman-bharat',title:'आयुष्मान भारत – प्रधानमंत्री जन आरोग्य योजना',english:'Ayushman Bharat PM JAY',category:'swasthya',state:'central',summary:'पात्र परिवारों के लिए अस्पताल में उपचार से जुड़ी सहायता। अपनी पात्रता official source से जाँचें।',benefit:'अस्पताल में इलाज के लिए स्वास्थ्य सुरक्षा',sourceUrl:'',priority:true,rules:[]},
 {...base,slug:'pm-awas-gramin',title:'प्रधानमंत्री आवास योजना – ग्रामीण',english:'PM Awas Yojana Gramin Housing',category:'awas',state:'central',summary:'ग्रामीण परिवारों के लिए आवास सहायता से जुड़ी योजना। चयन और लाभ की शर्तों का सत्यापन बाकी है।',benefit:'पात्र ग्रामीण परिवारों को आवास सहायता',sourceUrl:'',priority:false,rules:[{field:'rural',op:'eq',value:true,label:'ग्रामीण क्षेत्र में निवास (उदाहरण नियम)'}]},
 {...base,slug:'mp-scholarship',title:'मध्य प्रदेश छात्रवृत्ति सहायता',english:'MP Scholarship Students Education',category:'shiksha',state:'madhya-pradesh',summary:'विद्यार्थियों को छात्रवृत्ति योजनाओं तक पहुँचाने वाला उदाहरण रिकॉर्ड। पाठ्यक्रम और श्रेणी की शर्तें अलग हो सकती हैं।',benefit:'पढ़ाई के लिए सहायता की जानकारी',sourceUrl:'',priority:false,rules:[{field:'occupation',op:'eq',value:'student',label:'विद्यार्थी (उदाहरण नियम)'}]},
 {...base,slug:'social-pension',title:'सामाजिक सुरक्षा पेंशन',english:'Social Security Old Age Pension',category:'pension',state:'madhya-pradesh',summary:'वरिष्ठ नागरिकों के लिए पेंशन सहायता का उदाहरण। आयु, आय और अन्य शर्तों की सरकारी पुष्टि जरूरी है।',benefit:'वरिष्ठ नागरिकों के लिए सामाजिक सुरक्षा',sourceUrl:'',priority:false,rules:[{field:'age',op:'gte',value:60,label:'60 वर्ष या अधिक (केवल उदाहरण नियम)'}]},
 {...base,slug:'employment-support',title:'स्वरोज़गार सहायता',english:'Self Employment Business Support',category:'rojgar',state:'madhya-pradesh',summary:'अपना काम शुरू करने से जुड़ी सहायता खोजने का उदाहरण रिकॉर्ड। यह किसी चालू योजना का सत्यापित विवरण नहीं है।',benefit:'अपना काम शुरू करने के अवसर खोजें',sourceUrl:'',priority:false,rules:[{field:'occupation',op:'eq',value:'self-employed',label:'स्वरोज़गार से जुड़े नागरिक (उदाहरण नियम)'}]},
 {...base,slug:'ration-support',title:'खाद्य सुरक्षा और राशन सहायता',english:'Food Security Ration Support',category:'khadya',state:'central',summary:'राशन और खाद्य सहायता की जानकारी का उदाहरण। स्थानीय पात्रता और आवेदन प्रक्रिया की पुष्टि करें।',benefit:'परिवार के लिए खाद्य सुरक्षा की जानकारी',sourceUrl:'',priority:false,rules:[]},
 {...base,slug:'mukhyamantri-seekho-kamao',title:'मुख्यमंत्री सीखो कमाओ योजना',english:'Mukhyamantri Seekho Kamao Yojana Skill Training',category:'rojgar',state:'madhya-pradesh',summary:'मध्य प्रदेश के युवाओं को ऑन-जॉब ट्रेनिंग के दौरान ₹8,000–10,000 स्टाइपेंड और MMSKY प्रशिक्षण प्रमाण पत्र।',benefit:'₹8,000–₹10,000 प्रति माह स्टाइपेंड · प्रशिक्षण प्रमाण पत्र',department:'कौशल विकास एवं रोज़गार विभाग, मध्य प्रदेश',sourceUrl:'https://mmsky.mp.gov.in/',priority:true,rules:[{field:'age',op:'gte',value:18,label:'न्यूनतम 18 वर्ष'},{field:'age',op:'lte',value:29,label:'अधिकतम 29 वर्ष'}]},
 {...base,slug:'kisan-kalyan',title:'मुख्यमंत्री किसान कल्याण योजना',english:'Mukhyamantri Kisan Kalyan Yojana Financial Support',category:'kisan',state:'madhya-pradesh',summary:'मध्य प्रदेश के PM-KISAN पंजीकृत किसानों को अतिरिक्त ₹6,000 प्रति वर्ष। दोनों योजनाओं से कुल ₹12,000/वर्ष।',benefit:'₹6,000 प्रति वर्ष अतिरिक्त · दो किस्तों में',department:'किसान कल्याण तथा कृषि विकास विभाग, मध्य प्रदेश',sourceUrl:'https://mpwcdmis.gov.in/',priority:true,rules:[{field:'occupation',op:'eq',value:'farmer',label:'PM-KISAN पंजीकृत किसान परिवार'}]},
 {...base,slug:'mp-gaon-ki-beti',title:'गांव की बेटी योजना',english:'Gaon Ki Beti Yojana Rural Girl Scholarship',category:'shiksha',state:'madhya-pradesh',summary:'ग्रामीण क्षेत्र की 12वीं में 60% से अधिक अंक पाने वाली छात्राओं को उच्च शिक्षा के लिए ₹500/माह छात्रवृत्ति।',benefit:'₹500 प्रति माह · 10 माह · कुल ₹5,000 प्रति वर्ष',department:'उच्च शिक्षा विभाग, मध्य प्रदेश',sourceUrl:'https://scholarshipportal.mp.nic.in/',priority:true,rules:[{field:'gender',op:'eq',value:'female',label:'केवल छात्राओं के लिए'},{field:'occupation',op:'eq',value:'student',label:'उच्च शिक्षा में प्रवेश लिया हो'}]},
 {...base,slug:'mp-board-laptop',title:'MP मुफ्त लैपटॉप योजना',english:'MP Free Laptop Yojana',category:'shiksha',state:'madhya-pradesh',summary:'एमपी बोर्ड 12वीं की परीक्षा में उत्कृष्ट अंक लाने वाले मेधावी छात्रों को लैपटॉप खरीदने के लिए आर्थिक सहायता।',benefit:'लैपटॉप खरीदने के लिए ₹25,000',department:'स्कूल शिक्षा विभाग, मध्य प्रदेश',sourceUrl:'https://shikshaportal.mp.gov.in/',priority:true,rules:[{field:'occupation',op:'eq',value:'student',label:'मध्य प्रदेश बोर्ड का छात्र'}]},
 {...base,slug:'sambal-yojana',title:'मुख्यमंत्री जन कल्याण संबल योजना',english:'Mukhyamantri Jan Kalyan Sambal Yojana Unorganized Workers',category:'rojgar',state:'madhya-pradesh',summary:'असंगठित श्रमिकों को संबल कार्ड से दुर्घटना बीमा, मातृत्व सहायता, बिजली बिल माफी और अंत्येष्टि सहायता।',benefit:'दुर्घटना मृत्यु: ₹4 लाख · मातृत्य: ₹16,000 · अंत्येष्टि: ₹5,000',department:'श्रम विभाग, मध्य प्रदेश',sourceUrl:'https://sambal.mp.gov.in/',priority:true,rules:[{field:'occupation',op:'eq',value:'worker',label:'असंगठित क्षेत्र के श्रमिक'}]},
 {...base,slug:'ladli-laxmi',title:'लाड़ली लक्ष्मी योजना',english:'Ladli Laxmi Yojana Girl Child Certificate Education',category:'mahila',state:'madhya-pradesh',summary:'मध्य प्रदेश में जन्मी बालिकाओं के नाम ₹1,43,000 का लाड़ली लक्ष्मी प्रमाण पत्र। पढ़ाई में किस्तें और 21 वर्ष पर ₹1 लाख।',benefit:'₹1,43,000 का प्रमाण पत्र · 6वीं से 12वीं किस्तें · 21 वर्ष पर ₹1 लाख',department:'महिला एवं बाल विकास विभाग, मध्य प्रदेश',sourceUrl:'https://ladlilaxmi.mp.gov.in/',priority:true,rules:[{field:'gender',op:'eq',value:'female',label:'केवल बालिकाओं के लिए'}]},
 {...base,slug:'pm-vishwakarma',title:'प्रधानमंत्री विश्वकर्मा योजना',english:'PM Vishwakarma Artisan Toolkit Loan',category:'rojgar',state:'central',summary:'पारंपरिक कारीगरों व शिल्पकारों को ₹15,000 टूलकिट ई-वाउचर, 5% रियायती ब्याज पर ₹3 लाख तक कोलेटरल-मुक्त ऋण एवं कौशल प्रशिक्षण।',benefit:'₹15,000 टूलकिट ई-वाउचर · ₹3 लाख तक कम ब्याज ऋण',department:'सूक्ष्म, लघु एवं मध्यम उद्यम मंत्रालय, भारत सरकार',sourceUrl:'https://pmvishwakarma.gov.in/',priority:true,rules:[{field:'occupation',op:'eq',value:'worker',label:'18 पारंपरिक शिल्पों से जुड़े कारीगर/दस्तकार'},{field:'age',op:'gte',value:18,label:'न्यूनतम 18 वर्ष'}]},
 {...base,slug:'pm-surya-ghar',title:'पीएम सूर्य घर: मुफ्त बिजली योजना',english:'PM Surya Ghar Muft Bijli Rooftop Solar',category:'awas',state:'central',summary:'घरेलू छतों पर सोलर सिस्टम लगाने पर ₹78,000 तक सीधी सरकारी सब्सिडी और हर महीने 300 यूनिट तक मुफ्त बिजली।',benefit:'₹78,000 तक सोलर सब्सिडी · 300 यूनिट/माह मुफ्त बिजली',department:'नवीन एवं नवीकरणीय ऊर्जा मंत्रालय, भारत सरकार',sourceUrl:'https://pmsuryaghar.gov.in/',priority:true,rules:[]},
 {...base,slug:'pm-mudra',title:'प्रधानमंत्री मुद्रा योजना (PMMY)',english:'Pradhan Mantri Mudra Yojana MSME Loan',category:'rojgar',state:'central',summary:'छोटे व्यापारियों, दुकानदारों और नए उद्यमियों को बिना गारंटी ₹50,000 से ₹10 लाख तक का आसान बैंक ऋण।',benefit:'₹50,000 से ₹10 लाख तक बिना गारंटी ऋण (शिशु, किशोर, तरुण)',department:'वित्तीय सेवाएं विभाग, वित्त मंत्रालय, भारत सरकार',sourceUrl:'https://financialservices.gov.in/',priority:true,rules:[{field:'occupation',op:'eq',value:'self-employed',label:'स्वरोज़गार या छोटा व्यवसाय करने वाले नागरिक'}]},
 {...base,slug:'atal-pension',title:'अटल पेंशन योजना (APY)',english:'Atal Pension Yojana Guaranteed Social Pension',category:'pension',state:'central',summary:'18 से 40 वर्ष के नागरिकों को 60 वर्ष की आयु के बाद ₹1,000 से ₹5,000 प्रति माह आजीवन सरकार समर्थित मासिक पेंशन।',benefit:'₹1,000 से ₹5,000 प्रति माह आजीवन गारंटीड पेंशन',department:'पेंशन निधि विनियामक और विकास प्राधिकरण (PFRDA)',sourceUrl:'https://financialservices.gov.in/',priority:true,rules:[{field:'age',op:'gte',value:18,label:'न्यूनतम 18 वर्ष'},{field:'age',op:'lte',value:40,label:'अधिकतम 40 वर्ष'}]},
 {...base,slug:'pm-ujjwala',title:'प्रधानमंत्री उज्ज्वला योजना 2.0',english:'PM Ujjwala Yojana Free LPG Connection',category:'mahila',state:'central',summary:'निर्धन परिवारों की महिला मुखिया को पूर्णतः निःशुल्क LPG गैस कनेक्शन, पहला भरा सिलेंडर और गैस चूल्हा।',benefit:'निःशुल्क नया गैस कनेक्शन · पहला भरा सिलेंडर व चूल्हा मुफ्त',department:'पेट्रोलियम एवं प्राकृतिक गैस मंत्रालय, भारत सरकार',sourceUrl:'https://pmuy.gov.in/',priority:true,rules:[{field:'gender',op:'eq',value:'female',label:'केवल वयस्क महिलाएं (18+ वर्ष)'},{field:'age',op:'gte',value:18,label:'न्यूनतम 18 वर्ष'}]},
];

const baseSeeds: Scheme[] = originalSeeds.map(s => ({ ...s, ...officialContent[s.slug] }));
const seedMap = new Map<string, Scheme>();
for (const s of baseSeeds) {
  seedMap.set(s.slug, s);
}
for (const s of mpSchemes) {
  if (!seedMap.has(s.slug)) {
    seedMap.set(s.slug, s);
  }
}

export const seeds: Scheme[] = Array.from(seedMap.values());
