import type { Scheme } from '../domain';

export const socialSecurityPensionContent: Partial<Scheme> = {
  status: 'ACTIVE',
  priority: true,
  isSample: false,
  verifiedAt: '2026-10-05T00:00:00.000Z',
  nextReviewAt: '2027-01-05T00:00:00.000Z',
  title: 'Social Security Pension Portal MP',
  english: 'Social Security Pension Portal MP',
  category: 'pension',
  state: 'madhya-pradesh',
  summary: 'मध्य प्रदेश में Social Security Pension Portal (सामाजिक सुरक्षा पेंशन पोर्टल) के माध्यम से समग्र सामाजिक सुरक्षा पेंशन योजना की जानकारी, ऑनलाइन आवेदन, आवेदन की स्थिति, पेंशन पासबुक और ₹600 पेंशन का विवरण।',
  summaryEn: 'Information regarding the Social Security Pension Portal MP, online application, application status, pension passbook, and the ₹600 monthly pension for eligible beneficiaries in Madhya Pradesh.',
  seoDescription: 'Social Security Pension Portal MP 2026: मध्य प्रदेश सामाजिक सुरक्षा पेंशन के लिए ऑनलाइन आवेदन (Online Apply), Pension Status, Passbook और ₹600 पेंशन की पूरी जानकारी।',
  benefit: 'पात्र निराश्रित वृद्ध, कल्याणी, परित्यक्ता और दिव्यांग हितग्राहियों को ₹600 प्रति माह पेंशन (राज्यांश मद से)',
  benefitEn: '₹600 per month pension for eligible destitute elderly, Kalyani, abandoned women, and disabled beneficiaries.',
  department: 'सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग, मध्य प्रदेश',
  imageUrl: '/social-security-pension-mp.jpg',
  sourceUrl: 'https://socialsecurity.mp.gov.in/Home.aspx',
  applicationUrl: 'https://socialsecurity.mp.gov.in/Home.aspx',
  documents: [
    'पासपोर्ट साइज फोटो',
    'आयु प्रमाण पत्र',
    'BPL या निराश्रित होने का प्रमाण (जहां लागू हो)',
    'दिव्यांगता प्रमाणपत्र (दिव्यांगजनों के लिए)',
    'कल्याणी/विधवा संबंधी प्रमाण (जहां लागू हो)',
    'परित्यक्तता से संबंधित प्रमाण (जहां लागू हो)',
    'आधार कार्ड',
    'बैंक पासबुक (आधार और DBT लिंक)'
  ],
  documentsEn: [
    'Passport size photograph',
    'Age proof',
    'BPL or destitution proof (if applicable)',
    'Disability certificate (for disabled)',
    'Kalyani/Widow proof (if applicable)',
    'Abandonment proof (if applicable)',
    'Aadhaar Card',
    'Bank Passbook (Aadhaar and DBT linked)'
  ],
  steps: [
    'Online: Social Security Pension Portal (socialsecurity.mp.gov.in) पर जाएं।',
    'संबंधित Pension Scheme चुनें और Eligibility देखें।',
    'आवेदन भरें और आवश्यक Documents अपलोड करें।',
    'आवेदन Submit करें और Application Status के लिए रसीद/रेफरेंस नंबर सुरक्षित रखें।',
    'Offline: ग्रामीण क्षेत्र में ग्राम पंचायत/जनपद पंचायत और शहरी क्षेत्र में नगर निगम/नगर पालिका/नगर परिषद या लोक सेवा केंद्र से आवेदन करें।'
  ],
  stepsEn: [
    'Online: Visit the Social Security Pension Portal (socialsecurity.mp.gov.in).',
    'Select the relevant Pension Scheme and check Eligibility.',
    'Fill the application form and upload necessary Documents.',
    'Submit the application and keep the receipt/reference number for checking Application Status.',
    'Offline: Apply through Gram Panchayat/Janpad Panchayat in rural areas and Nagar Nigam/Nagar Palika/Nagar Parishad or Lok Seva Kendra in urban areas.'
  ],
  rules: [],
  sourceNotes: 'आधिकारिक वेबकास्ट और पोर्टल डेटा पर आधारित। पेंशन राशि और पात्रता योजना के अनुसार भिन्न हो सकती है।',
  detailedDescription: [
  '<h1>Social Security Pension Portal MP 2026: Online Apply, Pension Status, Passbook और ₹600 Pension की पूरी जानकारी</h1>',
  '<p>अंतिम अपडेट: 5 अक्टूबर 2026</p>',
  '<p>अगर आप Social Security Pension Portal MP, सामाजिक सुरक्षा पेंशन पोर्टल, MP Pension Online Apply, MP Pension Status, Pension Passbook या मध्य प्रदेश में मिलने वाली सामाजिक सुरक्षा पेंशन की जानकारी खोज रहे हैं, तो सही सरकारी पोर्टल जानना सबसे जरूरी है।</p>',
  '<p>मध्य प्रदेश सरकार का Social Security Pension Portal सामाजिक सुरक्षा पेंशन से जुड़ी कई सेवाओं के लिए इस्तेमाल किया जाता है। इस पोर्टल पर पेंशन योजनाओं की जानकारी के साथ ऑनलाइन आवेदन, आवेदन की स्थिति, पेंशन पासबुक, बकाया राशि और पेंशन बंद होने का कारण जैसी सुविधाएं उपलब्ध हैं।</p>',
  '<p>समग्र सामाजिक सुरक्षा पेंशन योजना के अंतर्गत पात्र हितग्राहियों को विभागीय जानकारी के अनुसार ₹600 प्रति माह पेंशन दी जाती है। हालांकि अलग-अलग पेंशन योजनाओं की पात्रता और नियम अलग हो सकते हैं, इसलिए आवेदन करने से पहले अपनी category और संबंधित योजना की शर्तें देखना जरूरी है।</p>',
  '<h2>Social Security Pension Portal MP क्या है?</h2>',
  '<p>Social Security Pension Portal MP मध्य प्रदेश सरकार के सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग से संबंधित आधिकारिक online platform है।</p>',
  '<p>इस portal का इस्तेमाल सामाजिक सुरक्षा से जुड़ी विभिन्न pension schemes की जानकारी और beneficiary services के लिए किया जाता है। अगर आपको MP social security pension online apply, pension status check, pension passbook या payment से जुड़ी जानकारी चाहिए, तो यह portal सबसे महत्वपूर्ण सरकारी स्रोत है।</p>',
  '<h2>Official Portal</h2>',
  '<ul>',
  '<li><strong>Social Security Pension Portal MP:</strong> <a href="https://socialsecurity.mp.gov.in/Home.aspx" target="_blank" rel="noopener noreferrer">https://socialsecurity.mp.gov.in/Home.aspx</a></li>',
  '<li><strong>सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग:</strong> <a href="https://socialjustice.mp.gov.in/" target="_blank" rel="noopener noreferrer">https://socialjustice.mp.gov.in/</a></li>',
  '</ul>',
  '<p>अगर आप मध्य प्रदेश की दूसरी सरकारी योजनाओं की जानकारी भी देख रहे हैं, तो हमारा <a href="https://chatgpt.com/madhya-pradesh-government-schemes/">मध्य प्रदेश की सरकारी योजनाओं का पूरा गाइड</a> भी पढ़ सकते हैं।</p>',
  '<h2>Social Security Pension Portal पर कौन-कौन सी सुविधाएं मिलती हैं?</h2>',
  '<p>Portal खोलने पर आपको सिर्फ pension scheme की जानकारी ही नहीं मिलती, बल्कि कई practical services भी दिखाई देती हैं।</p>',
  '<p>इनमें प्रमुख हैं:</p>',
  '<ul>',
  '<li>Online Pension Application</li>',
  '<li>Application Status</li>',
  '<li>Pension Passbook</li>',
  '<li>Arrear Passbook</li>',
  '<li>Pension Stoppage Reason</li>',
  '<li>Pension Payment Information</li>',
  '<li>Unsuccessful Payment Information</li>',
  '<li>Pension Schemes की जानकारी</li>',
  '</ul>',
  '<p>यानी अगर आपने आवेदन कर दिया है और अब MP Pension Status देखना चाहते हैं, तो इसी portal से शुरुआत करनी चाहिए।</p>',
  '<p>अगर आप मध्य प्रदेश की दूसरी pension schemes की जानकारी देखना चाहते हैं, तो <a href="https://chatgpt.com/mp-pension-schemes/">MP Pension Schemes की पूरी जानकारी</a> भी पढ़ सकते हैं।</p>',
  '<h2>Social Security Pension MP में कितनी पेंशन मिलती है?</h2>',
  '<p>मध्य प्रदेश सरकार के सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग की उपलब्ध योजना जानकारी के अनुसार समग्र सामाजिक सुरक्षा पेंशन योजना के पात्र वृद्ध, कल्याणी, परित्यक्ता और दिव्यांग हितग्राहियों को ₹600 प्रति माह राज्यांश मद से पेंशन दी जाती है।</p>',
  '<p>यहां एक बात समझना जरूरी है कि Social Security Pension Portal पर कई अलग-अलग pension schemes उपलब्ध हैं। इसलिए हर scheme में मिलने वाली राशि या पात्रता एक जैसी नहीं होती।</p>',
  '<p><a href="https://chatgpt.com/mp-pension-schemes/" target="_blank" rel="noopener noreferrer">MP Pension Amount और सभी पेंशन योजनाओं की जानकारी</a></p>',
  '<h2>Social Security Pension MP के लिए कौन पात्र है?</h2>',
  '<p>पात्रता इस बात पर निर्भर करती है कि आप किस pension scheme के अंतर्गत आवेदन कर रहे हैं।</p>',
  '<ul>',
  '<li>निराश्रित वृद्ध</li>',
  '</ul>',
  '<p>समग्र सामाजिक सुरक्षा पेंशन योजना की उपलब्ध जानकारी के अनुसार 60 वर्ष या उससे अधिक आयु के निराश्रित वृद्ध पात्र हो सकते हैं।</p>',
  '<p>केवल 60 वर्ष की आयु पूरी होना ही पर्याप्त नहीं माना जाना चाहिए। संबंधित योजना की अन्य शर्तें भी पूरी करनी होती हैं।</p>',
  '<ul>',
  '<li>कल्याणी महिला</li>',
  '</ul>',
  '<p>निर्धारित शर्तों को पूरा करने वाली 18 वर्ष से अधिक आयु की कल्याणी महिला योजना का लाभ ले सकती है। विभागीय जानकारी में आयकरदाता न होने और कुछ अन्य शर्तों का भी उल्लेख है।</p>',
  '<ul>',
  '<li>परित्यक्ता महिला</li>',
  '</ul>',
  '<p>18 वर्ष से अधिक और 59 वर्ष तक की परित्यक्ता महिला, जो निर्धारित आर्थिक शर्तें पूरी करती हो, पात्र हो सकती है।</p>',
  '<ul>',
  '<li>दिव्यांगजन</li>',
  '</ul>',
  '<p>विभागीय जानकारी के अनुसार 40 प्रतिशत या उससे अधिक दिव्यांगता वाले पात्र दिव्यांगजन के लिए सामाजिक सुरक्षा पेंशन का प्रावधान है।</p>',
  '<ul>',
  '<li>वृद्धाश्रम में रहने वाले वृद्ध</li>',
  '</ul>',
  '<p>60 वर्ष से अधिक आयु के वृद्धाश्रम में रहने वाले अंत:वासी भी संबंधित पात्र श्रेणी में शामिल हैं।</p>',
  '<h2>Social Security Pension के लिए जरूरी दस्तावेज</h2>',
  '<p>दस्तावेज आपकी pension category पर निर्भर करते हैं। सामान्य रूप से विभागीय जानकारी में निम्न प्रकार के documents का उल्लेख मिलता है:</p>',
  '<ul>',
  '<li>फोटो</li>',
  '<li>आयु प्रमाण</li>',
  '<li>BPL या निराश्रित होने का प्रमाण, जहां लागू हो</li>',
  '<li>दिव्यांगता प्रमाणपत्र, जहां लागू हो</li>',
  '<li>कल्याणी/विधवा संबंधी प्रमाण, जहां लागू हो</li>',
  '<li>परित्यक्तता से संबंधित प्रमाण, जहां लागू हो</li>',
  '</ul>',
  '<p>इसलिए Social Security Pension Documents की एक ही सूची सभी applicants पर लागू नहीं होती।</p>',
  '<p>आवेदन से पहले अपनी category के अनुसार documents तैयार करना बेहतर रहेगा।</p>',
  '<h2>Social Security Pension Online Apply कैसे करें?</h2>',
  '<p>यदि आप Social Security Pension Online Apply करना चाहते हैं, तो official Social Security Pension Portal से शुरुआत करें।</p>',
  '<p>सबसे पहले portal खोलें और संबंधित pension scheme तथा उपलब्ध online application option देखें। आवेदन करते समय वही जानकारी और documents दें जो current portal पर मांगे जा रहे हों।</p>',
  '<p>सामान्य प्रक्रिया इस तरह समझ सकते हैं:</p>',
  '<p>Official Portal खोलें → संबंधित Pension Scheme चुनें → Eligibility देखें → आवेदन भरें → Documents दें → आवेदन Submit करें → Application Status देखें</p>',
  '<p>Portal की screen और options समय के साथ बदल सकते हैं, इसलिए आवेदन करते समय website पर दिए गए current instructions को ही follow करें।</p>',
  '<h2>क्या Social Security Pension का Offline आवेदन भी होता है?</h2>',
  '<p>हाँ। यदि online आवेदन करने में परेशानी हो, तो निर्धारित माध्यम से offline application भी किया जा सकता है।</p>',
  '<p>विभागीय जानकारी के अनुसार ग्रामीण क्षेत्र में ग्राम पंचायत/जनपद पंचायत और शहरी क्षेत्र में नगर निगम, नगर पालिका या नगर परिषद के माध्यम से आवेदन किया जा सकता है। लोक सेवा केंद्र भी आवेदन का एक माध्यम है।</p>',
  '<p>यानी जिन लोगों को online portal समझने में परेशानी होती है, वे स्थानीय सरकारी कार्यालय की सहायता ले सकते हैं।</p>',
  '<h2>MP Pension Status कैसे Check करें?</h2>',
  '<p>अगर आपने pension के लिए आवेदन कर दिया है और जानना चाहते हैं कि application approve हुआ या नहीं, तो Social Security Pension Portal पर View Application Status की सुविधा उपलब्ध है।</p>',
  '<p>Portal खोलें और status check के लिए मांगी गई application details भरें।</p>',
  '<p>Status देखते समय घबराने की जरूरत नहीं है अगर application तुरंत approved नहीं दिख रहा। Documents verification और संबंधित विभागीय प्रक्रिया पूरी होने में समय लग सकता है।</p>',
  '<ul>',
  '<li>Pension Passbook कैसे देखें?</li>',
  '</ul>',
  '<p>Social Security Pension Portal पर View Pension Passbook की सुविधा उपलब्ध है।</p>',
  '<p>अगर आपको यह देखना है कि pension की राशि कब जमा हुई, payment history क्या रही या पिछले installments की स्थिति क्या है, तो pension passbook काफी उपयोगी है।</p>',
  '<p>Portal पर Arrear Passbook की सुविधा भी उपलब्ध है, जिससे बकाया भुगतान की जानकारी देखी जा सकती है।</p>',
  '<p>अगर आपकी pension का पैसा नहीं आया है, तो सिर्फ बैंक account check करने के बजाय portal पर payment और passbook information भी देखना चाहिए।</p>',
  '<h2>Pension नहीं आ रही है तो क्या करें?</h2>',
  '<p>अगर पहले pension आती थी लेकिन अब नहीं आ रही, तो सीधे नया आवेदन करने से पहले कारण जानना ज्यादा जरूरी है।</p>',
  '<p>Social Security Pension Portal पर Pension Stoppage Reason देखने की सुविधा उपलब्ध है।</p>',
  '<p>इसके अलावा portal पर unsuccessful payment से संबंधित जानकारी भी उपलब्ध है।</p>',
  '<p>ऐसी स्थिति में इन चीजों को check करें:</p>',
  '<p>Pension Status → Stoppage Reason → Payment Information → Bank Details → Aadhaar/eKYC</p>',
  '<p>जरूरत पड़ने पर ग्राम पंचायत, नगर निकाय या संबंधित अधिकारी से संपर्क करें।</p>',
  '<h2>Social Security Pension का पैसा कब आता है?</h2>',
  '<p>पेंशन का भुगतान सरकारी payment system के माध्यम से किया जाता है। Social Security Pension Portal पर payment-related information और unsuccessful payments के लिए भी services उपलब्ध हैं।</p>',
  '<p>2026 में सरकारी webcast records में social security pension amount transfer से जुड़े कार्यक्रम भी दर्ज हैं। इसलिए pension payment की सरकारी प्रक्रिया 2026 में सक्रिय रही है।</p>',
  '<p>लेकिन किसी individual beneficiary के खाते में exact payment date अलग हो सकती है। इसलिए payment की जानकारी देखने के लिए portal की passbook और payment status को प्राथमिकता दें।</p>',
  '<h2>Aadhaar eKYC और Bank Account का क्या महत्व है?</h2>',
  '<p>Pension payment में सही bank details और Aadhaar-related verification महत्वपूर्ण हो सकते हैं।</p>',
  '<p>सामाजिक न्याय विभाग की उपलब्ध जानकारी में Aadhaar eKYC, Aadhaar-linked bank account और DBT से संबंधित निर्देश दिए गए हैं।</p>',
  '<p>इसलिए अगर pension approve होने के बावजूद payment में समस्या है, तो यह भी check करें कि:</p>',
  '<ul><li>Bank account सही है या नहीं</li><li>Aadhaar details सही हैं या नहीं</li><li>eKYC complete है या नहीं</li><li>DBT से संबंधित कोई समस्या तो नहीं है</li></ul>',
  '<h2>Social Security Pension में आवेदन शुल्क कितना है?</h2>',
  '<p>समग्र सामाजिक सुरक्षा पेंशन योजना के लिए आवेदन निःशुल्क है।</p>',
  '<p>अगर कोई व्यक्ति सिर्फ सरकारी pension application के नाम पर अनधिकृत पैसा मांगता है, तो payment करने से पहले संबंधित कार्यालय या authorized service center की पुष्टि करें।</p>',
  '<h2>Social Security Pension आवेदन में कितना समय लगता है?</h2>',
  '<p>उपलब्ध सरकारी scheme information में आवेदन के लिए 15 कार्य दिवस की समय सीमा दर्ज है।</p>',
  '<p>हालांकि document verification और स्थानीय स्तर की processing के कारण वास्तविक समय अलग हो सकता है।</p>',
  '<h2>Social Security Pension के लिए आवेदन कहां करें?</h2>',
  '<p>आप अपनी स्थिति के अनुसार:</p>',
  '<ul><li>Online: Social Security Pension Portal</li><li>ग्रामीण क्षेत्र: ग्राम पंचायत/जनपद पंचायत</li><li>शहरी क्षेत्र: नगर निगम/नगर पालिका/नगर परिषद</li><li>अन्य माध्यम: लोक सेवा केंद्र</li></ul>',
  '<p>का उपयोग कर सकते हैं।</p>',
  '<h2>Social Security Pension Portal MP पर कौन-कौन सी Pension Schemes हैं?</h2>',
  '<p>Portal पर अलग-अलग सामाजिक सुरक्षा pension schemes उपलब्ध हैं। इनमें प्रमुख रूप से:</p>',
  '<ul><li>सामाजिक सुरक्षा वृद्धावस्था पेंशन योजना</li><li>सामाजिक सुरक्षा परित्यक्ता पेंशन योजना</li><li>सामाजिक सुरक्षा निःशक्त पेंशन योजना</li><li>मुख्यमंत्री सामाजिक सुरक्षा कल्याणी पेंशन योजना</li><li>मुख्यमंत्री अविवाहिता पेंशन योजना</li><li>मुख्यमंत्री कन्या अभिभावक पेंशन योजना</li><li>इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना</li><li>इंदिरा गांधी राष्ट्रीय विधवा पेंशन योजना</li><li>इंदिरा गांधी राष्ट्रीय दिव्यांग पेंशन योजना</li></ul>',
  '<p>शामिल हैं।</p>',
  '<p>इसलिए application करने से पहले यह देखना जरूरी है कि आप किस योजना के लिए eligible हैं।</p>',
  '<h2>Social Security Pension और वृद्धावस्था पेंशन में अंतर</h2>',
  '<p>कई लोग Social Security Pension और Old Age Pension को एक ही योजना समझ लेते हैं। ऐसा जरूरी नहीं है।</p>',
  '<p>मध्य प्रदेश Social Security Pension Portal पर राज्य की social security schemes के साथ इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन जैसी national schemes भी अलग से मौजूद हैं।</p>',
  '<p>यानी उम्र समान होने के बावजूद व्यक्ति अलग-अलग scheme के अलग eligibility criteria में आ सकता है।</p>',
  '<p>इसलिए सिर्फ “60 वर्ष की उम्र” देखकर किसी एक pension scheme में आवेदन करना सही नहीं होगा।</p>',
  '<h2>Social Security Pension Portal पर Payment Status कैसे देखें?</h2>',
  '<p>अगर pension का पैसा आने का इंतजार है, तो सबसे पहले official portal पर available payment-related information देखें।</p>',
  '<p>Portal पर payment information के अलावा unsuccessful payment की जानकारी भी उपलब्ध है।</p>',
  '<p>अगर payment fail दिख रहा है, तो bank account और Aadhaar-related information की भी जांच करें।</p>',
  '<p>जरूरत होने पर संबंधित local body या pension officer से संपर्क करें।</p>',
  '<h2>Social Security Pension Portal MP की मुख्य जानकारी</h2>',
  '<div class="table-container"><table class="info-table"><thead><tr><th>जानकारी</th><th>विवरण</th></tr></thead><tbody><tr><td>Portal का नाम</td><td>Social Security Pension Portal MP</td></tr><tr><td>राज्य</td><td>मध्य प्रदेश</td></tr><tr><td>संबंधित विभाग</td><td>सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग</td></tr><tr><td>मुख्य उपयोग</td><td>Pension application और beneficiary services</td></tr><tr><td>समग्र सामाजिक सुरक्षा पेंशन</td><td>₹600 प्रति माह</td></tr><tr><td>Online Apply</td><td>उपलब्ध</td></tr><tr><td>Application Status</td><td>उपलब्ध</td></tr><tr><td>Pension Passbook</td><td>उपलब्ध</td></tr><tr><td>Arrear Passbook</td><td>उपलब्ध</td></tr><tr><td>Pension Stoppage Reason</td><td>उपलब्ध</td></tr><tr><td>Payment Information</td><td>उपलब्ध</td></tr><tr><td>आवेदन शुल्क</td><td>निःशुल्क</td></tr><tr><td>Online Portal</td><td>socialsecurity.mp.gov.in</td></tr></tbody></table></div>',
  '<h2>Social Security Pension Portal MP का Official Link</h2>',
  '<ul><li><strong>Social Security Pension Portal MP:</strong> <a href="https://socialsecurity.mp.gov.in/Home.aspx" target="_blank" rel="noopener noreferrer">https://socialsecurity.mp.gov.in/Home.aspx</a></li></ul>',
  '<p>सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग, मध्य प्रदेश:</p>',
  '<p><a href="https://socialjustice.mp.gov.in/" target="_blank" rel="noopener noreferrer">https://socialjustice.mp.gov.in/</a></p>',
  '<h2>आधिकारिक स्रोत</h2>',
  '<p>Social Security Pension Portal MP</p>',
  '<p><a href="https://socialsecurity.mp.gov.in/Home.aspx" target="_blank" rel="noopener noreferrer">https://socialsecurity.mp.gov.in/Home.aspx</a></p>',
  '<p>सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग, मध्य प्रदेश</p>',
  '<p><a href="https://socialjustice.mp.gov.in/" target="_blank" rel="noopener noreferrer">https://socialjustice.mp.gov.in/</a></p>',
  '<p>मध्य प्रदेश सरकार Services Portal</p>',
  '<p><a href="https://www.services.mp.gov.in/" target="_blank" rel="noopener noreferrer">https://www.services.mp.gov.in/</a></p>',
  '<p>मध्य प्रदेश Government Webcast</p>',
  '<p><a href="https://webcast.gov.in/mp/" target="_blank" rel="noopener noreferrer">https://webcast.gov.in/mp/</a></p>',
  '<h2>निष्कर्ष</h2>',
  '<p>मध्य प्रदेश में सामाजिक सुरक्षा पेंशन से जुड़ी online services के लिए Social Security Pension Portal MP सबसे महत्वपूर्ण सरकारी platforms में से एक है। यहां pension schemes की जानकारी के साथ online application, application status, pension passbook, arrear passbook और payment-related information जैसी सुविधाएं उपलब्ध हैं।</p>',
  '<p>समग्र सामाजिक सुरक्षा पेंशन योजना के तहत पात्र हितग्राहियों को विभागीय जानकारी के अनुसार ₹600 प्रति माह पेंशन दी जाती है। लेकिन सभी pension schemes के नियम एक जैसे नहीं हैं, इसलिए आवेदन करने से पहले अपनी category और संबंधित scheme की पात्रता जरूर जांचें।</p>',
  '<p>अगर आपका काम MP Pension Status Check, Pension Passbook, Social Security Pension Online Apply या pension payment की जानकारी लेना है, तो सीधे official Social Security Pension Portal का उपयोग करना सबसे बेहतर तरीका है।</p>',
  ],
  faqs: [
    {
      question: 'Social Security Pension Portal MP क्या है?',
      answer: 'यह मध्य प्रदेश सरकार का social security pension portal है, जहां अलग-अलग pension schemes की जानकारी, online application, application status, pension passbook और payment-related services उपलब्ध हैं।'
    },
    {
      question: 'Social Security Pension MP में कितने रुपये मिलते हैं?',
      answer: 'समग्र सामाजिक सुरक्षा पेंशन योजना के पात्र हितग्राहियों को विभागीय जानकारी के अनुसार ₹600 प्रति माह राज्यांश से पेंशन दी जाती है।'
    },
    {
      question: 'Social Security Pension की official website कौन सी है?',
      answer: 'Official portal है: https://socialsecurity.mp.gov.in/Home.aspx'
    },
    {
      question: 'MP Pension Status कैसे check करें?',
      answer: 'Social Security Pension Portal पर View Application Status service का उपयोग करके application status देखा जा सकता है।'
    },
    {
      question: 'MP Pension Passbook कैसे देखें?',
      answer: 'Official Social Security Pension Portal पर View Pension Passbook option उपलब्ध है।'
    },
    {
      question: 'Pension बंद हो गई है तो कारण कैसे पता करें?',
      answer: 'Portal पर Pension Stoppage Reason देखने की सुविधा उपलब्ध है।'
    },
    {
      question: 'क्या Social Security Pension Online Apply कर सकते हैं?',
      answer: 'हाँ। Social Security Pension Portal पर उपलब्ध online application service के माध्यम से संबंधित scheme के लिए आवेदन किया जा सकता है।'
    },
    {
      question: 'क्या pension application के लिए शुल्क लगता है?',
      answer: 'नहीं। समग्र सामाजिक सुरक्षा पेंशन योजना के लिए आवेदन निःशुल्क है।'
    },
    {
      question: 'Social Security Pension के लिए कौन पात्र है?',
      answer: 'समग्र सामाजिक सुरक्षा पेंशन योजना में निर्धारित शर्तों के अनुसार निराश्रित वृद्ध, पात्र कल्याणी, परित्यक्ता महिला, निर्धारित दिव्यांगजन और अन्य संबंधित श्रेणियां शामिल हैं।'
    },
    {
      question: 'क्या 60 साल के हर व्यक्ति को Social Security Pension मिलती है?',
      answer: 'नहीं। उम्र के साथ योजना में अन्य पात्रता शर्तें भी लागू हो सकती हैं। केवल 60 वर्ष की आयु पूरी होना अपने आप pension approval की गारंटी fixed नहीं है।'
    },
    {
      question: 'दिव्यांग pension के लिए कितने प्रतिशत disability चाहिए?',
      answer: 'विभागीय योजना जानकारी के अनुसार 40 प्रतिशत या उससे अधिक दिव्यांगता वाले पात्र दिव्यांगजन सामाजिक सुरक्षा पेंशन की संबंधित category में शामिल हो सकते हैं।'
    },
    {
      question: 'Pension का पैसा नहीं आए तो क्या करें?',
      answer: 'सबसे पहले portal पर payment information, passbook और pension stoppage reason देखें। इसके बाद bank account, Aadhaar/eKYC और DBT से संबंधित जानकारी की जांच करें।'
    },
    {
      question: 'Social Security Pension के लिए आवेदन कहां करें?',
      answer: 'Online आवेदन Social Security Pension Portal से किया जा सकता है। Offline आवेदन ग्राम पंचायत, जनपद पंचायत, नगर निगम, नगर पालिका, नगर परिषद या लोक सेवा केंद्र के माध्यम से किया जा सकता है।'
    },
    {
      question: 'क्या Pension Passbook online देख सकते हैं?',
      answer: 'हाँ। Official portal पर Pension Passbook की सुविधा उपलब्ध है। (Arrear Passbook के माध्यम से pension से संबंधित बकाया भुगतान की जानकारी भी देखी जा सकती है।)'
    },
    {
      question: 'Social Security Pension में आवेदन कितने दिन में होता है?',
      answer: 'उपलब्ध scheme information के अनुसार आवेदन के लिए 15 कार्य दिवस की समय सीमा दी गई है। वास्तविक समय verification और processing पर निर्भर कर सकता है।'
    },
    {
      question: 'क्या Social Security Pension Portal पर payment status देखा जा सकता है?',
      answer: 'हाँ। Portal पर district-wise और body-wise pension payment information के साथ unsuccessful payments की जानकारी भी उपलब्ध है।'
    }
  ],
  references: [
    {
      title: 'Social Security Pension Portal MP',
      organization: 'सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग',
      url: 'https://socialsecurity.mp.gov.in/Home.aspx',
      sections: ['Home Page', 'Schemes', 'Beneficiary Services'],
      accessedAt: '2026-10-05T00:00:00.000Z'
    },
    {
      title: 'सामाजिक न्याय एवं दिव्यांगजन सशक्तिकरण विभाग, मध्य प्रदेश',
      organization: 'Government of Madhya Pradesh',
      url: 'https://socialjustice.mp.gov.in/',
      sections: ['Departmental Website'],
      accessedAt: '2026-10-05T00:00:00.000Z'
    }
  ]
};
